### ISSUE TITLE
Upgrade Issue to 5.2

### ISSUE THREAD

**Issue by Sovenique** [orangehrm/orangehrm#1499]
**Environment details**
OrangeHRM version: 5.1/5.2 (Switching between)
OrangeHRM source: Docker Compose
Platform: Docker v20.10.17

Greetings,

I'm using this compose:

```
version: '3.9'
services:
  mariadb:
    image: mariadb:10.2
    volumes:
      - ./orangehrm-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=orangehrm
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=orangehrm
    restart: unless-stopped

  orangehrm:
    image: orangehrm/orangehrm:5.1   # switching this to 5.2 in order to upgrade
    ports:
      - 8181:80
      - 8443:443
    restart: unless-stopped
```
I'm experiencing a few problems,

1) Even when I'm NOT trying to upgrade the version, each time I `docker compose down/up`, I have to go through setup wizard again and configure it with the existing database. Is this what is meant to be? Is there a way to avoid this? A work-around for this is to mount `/var/www/html` from the `orangehrm` container to a Docker volume, but this may cause other kind of problems when trying to upgrade to newer versions, but when not switching versions it works. 

2) When I'm trying to upgrade to `5.2` from `5.1`, I have to go through the setup wizard, select that there's an existing installation and then configure it with the existing database. It succeeds but the problem here is that although the footer of the application says 5.2, I'm unauthorized to access the dashboard nor I can find any LDAP configuration (These are 5.2 features). If I clean everything up including the database volume and spin up the compose with `5.2` initially, everything works as expected. Why is this happening? Maybe when switching from `5.1` to `5.2`, the database schema is not upgraded properly? 

Please let me know, thank you for your time!

**Comment by RajithaKumara** [comment]
Hi @Sovenique 
1. This is because the application configuration file is not in persistence volume.
2. Anyway when you upgrade from 5.1 to 5.1 you have to go through the upgrader wizard as you need to upgrade the database schema.

Please refer [this sample compose file](https://gist.github.com/RajithaKumara/2d7b4013da9050a8bea0a2b771b8dfd8) for the first issue. Mounting `/var/www/html` also fine as you mentioned.

For your second question, we are researching on that to introduce upgrader script to work with containers. 
for the moment what you can do is

```yaml
version: '3.9'
services:
  mariadb:
    image: mariadb:10.2
    volumes:
      - ./orangehrm-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=orangehrm
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=orangehrm
    restart: unless-stopped

  orangehrm:
    image: orangehrm/orangehrm:5.2
    ports:
      - 8181:80
      - 8443:443
    restart: unless-stopped
    volumes:
      - ./orangehrm-5.2/src/config:/var/www/html/src/config
      - ./orangehrm-5.2/src/cache:/var/www/html/src/cache
      - ./orangehrm-5.2/src/log:/var/www/html/src/log
      - type: volume
        source: orangehrm-conf-5.2
        target: /var/www/html/lib/confs
        volume:
          nocopy: false #important

volumes:
  orangehrm-conf-5.2:
```

**Comment by RajithaKumara** [comment]
> I assume you made a typo at `Anyway when you upgrade from 5.1 to 5.1` and meant `5.1 to 5.2`, is that correct?

yes @Sovenique, sorry about that, it was my mistake, just edit the comment.

You can't downgrade, because application support only upgrade.
You can keep a backup of DB if you want to downgrade. But some data may loss if you restore to old backup.

**Comment by RajithaKumara** [comment]
Let me explain more on this.
When it comes to containers, for the moment application is not much friendly with container-based deployments. But it's not impossible. The only thing is may take some time to provide tools, which will help to easily deploy & scale the application. 

> Here upgrade means, upgrade the application code (which is in the docker image) as well as database. Because version to version database schema and master data may change. e.g. Based on the features new database tables will add, or drop

### First Approach;
This may suite if someone want's to upgrade and  see what are the features available in a release, and use it. Or simulate upgrade before try on live system.

![orangehrm-writable-folder-Page-2 drawio](https://user-images.githubusercontent.com/25487187/198539187-2db8bdc2-e495-4354-af7b-a6589bbef210.png)

Explanation;
You may have working OrangeHRM 5.1system. So if you want to upgrade it. you can backup database using `mysqldump` and source/restore that DB to new container (or create new database in same container).
Then use latest OrangeHRM (according to the diagram, OrangeHRM 5.2) image to upgrade the database. Once you access the web/app container via browser you will navigate to installer welcome page. so you need to select upgrade and continue on that path ([Upgrader guide](https://starterhelp.orangehrm.com/hc/en-us/articles/6937346912402-OrangeHRM-Starter-Upgrade-Guide-For-5x-versions-)). 
Once upgrade successful you have two working OrangeHRM systems, but different versions. But don't use both, because it's two databases. So use latest release if you are happy with it or stay old release if you are happy with it. But make sure to live only one system.

### Second Approach;
Here make live system into maintenance mode and upgrade the production database to latest OrangeHRM version (according to the diagram, OrangeHRM 5.2). This approach will suite if you already check features from the [demo instance](https://opensource-demo.orangehrmlive.com) or local fresh installation and happy to upgrade to latest version.

![orangehrm-writable-folder-Page-2 drawio(1)](https://user-images.githubusercontent.com/25487187/198541751-45bb943f-f363-44ce-956f-a6745c0c49dd.png)

Explanation;
Before this upgrade (or any type of upgrade) approach, we are recommended to backup the database. Using this approach old system down  for few minutes, and new web/app container will be live as the production system.

### If you want to scale the web/app container (Not fully supported for the moment);
Yes, you can do. Make sure to use the below common volumes connected to all web/app containers.
```yaml
  orangehrm:
    image: orangehrm/orangehrm:5.2
    #...
    volumes:
      - ./orangehrm-5.2/src/config:/var/www/html/src/config
      - ./orangehrm-5.2/src/cache:/var/www/html/src/cache
      - ./orangehrm-5.2/src/log:/var/www/html/src/log
      - type: volume
        source: orangehrm-conf-5.2
        target: /var/www/html/lib/confs
        volume:
          nocopy: false #important
```
`/var/www/html/src/config`, `/var/www/html/src/cache`, `/var/www/html/src/log`, These paths are not much important to be connected to all web/app containers. But `/var/www/html/lib/confs` this is important as this contains DB connection details.

Please give your thoughts, happy to help.
