### ISSUE TITLE
Error when try Firing REST API for issueToken

### ISSUE THREAD

**Issue by Winniepoom** [orangehrm/orangehrm#1709]
### OrangeHRM version

5.4

### Environment details

- OrangeHRM source:orangehrm/orangehrm:5.4  
- Platform:Linux
- PHP version:
- Database and version:mariadb:10.2   
- Web server:Docker-Compose
- Browser:Postman

docker-compsoe.yml
```
version: "3.3"

services:

  orangehrm:
    image: orangehrm/orangehrm:5.4
    restart: unless-stopped
    ports:
      - "8200:80"
      - "8443:443"
    environment:
      - ORANGEHRM_DATABASE_HOST=mariadb
      - ORANGEHRM_DATABASE_USER=root
      - ORANGEHRM_DATABASE_PASSWORD=orangehrm
      - ORANGEHRM_DATABASE_NAME=orangehrm
      - PUID=998
      - PGID=100
    volumes:
      - ./orange:/orangehrm
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb

  mariadb:
    image: mariadb:10.2
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./db_orange:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=orangehrm
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=orangehrm
      - MYSQL_ROOT_HOST="192.168.32.183,192.168.32.190"  # needs to be enclosed with quotes
```

### Describe the bug

I try to follow this API instructor  https://github.com/orangehrm/orangehrm/wiki/REST-API  to get an issue Token, but when I try to firing API in postman I get this error in postman console ,any idea how to solve it ?
```
POST http://192.168.32.190:8200/index.php/oauth/issueToken
Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://192.168.32.190:8200/index.php/oauth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/./web/index.php/auth/login
Request Headers
User-Agent: PostmanRuntime/7.31.3
Accept: */*
Postman-Token: 652d9af7-50dc-4342-8074-0061bd2c2c81
Host: 192.168.32.190:8200
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```
![image](https://github.com/orangehrm/orangehrm/assets/107398226/331adfb3-278a-4077-a32e-c75e5e00bed4)

### To reproduce

- firing POST API in postman with this URL http://192.168.32.190:8200/index.php/oauth/issueToken

### Expected behavior

solve this error and get API working.
