### ISSUE TITLE
Docker compose install fails due to db connection issue

### ISSUE THREAD

**Issue by johncarterofmars** [orangehrm/orangehrm#1873]
### OrangeHRM version

5.7

### Environment details

- OrangeHRM source: Docker
- Platform: Ubuntu 22.04 Dig Ocean
- PHP version: NA
- Database and version: MariaDB 10.4
- Web server: NA
- Browser: Firefox, Brave, Chromium

### Describe the bug

I am using the following Docker Compose file: 
```
version: "3.3"
services:
  orangehrm:
    image: orangehrm/orangehrm:latest
    restart: unless-stopped
    ports:
      - "8200:80"
      - "8443:443"
    environment:
      - ORANGEHRM_DATABASE_HOST=mariadb
      - ORANGEHRM_DATABASE_USER=orangeuser
      - ORANGEHRM_DATABASE_PASSWORD=password
      - ORANGEHRM_DATABASE_NAME=orangehrm
      - PUID=998
      - PGID=100
    volumes:
      - ./orange:/orangehrm
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb

  mariadb:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - ./db_orange:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=orangehrm
```

Both containers will start, and I am able to access the web GUI to start the config process. I then enter the info for the db config:

![ksnip_20241001-180415](https://github.com/user-attachments/assets/b1ace75c-1bb4-4077-88f1-e99fd300f3d4)

No matter how many times I delete containers and volumes and create new ones, it won't let me past this point. Is my compose file missing something that allows OrangeHRM to talk to the Mariadb container?

Thank you.
