### ISSUE TITLE
Internal Error Occured

### ISSUE THREAD

**Issue by ramesh8830** [orangehrm/orangehrm#799]
**Environment details**
OrangeHRM version: [4.8]
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm)
Platform: Centos 8.4 (WHM CPanel)
PHP version: 7.3
Database and version: [8.0.25]
Web server: [Apache 2.4]

**Describe the bug**
Fresh Installation of orange crm give me an error "Internal Error Occurred" after successful installation. Works fine when installed on my windows machine with xampp

**What do you see instead:**
Internal Error Occurred

If issue related to any other
- symfony/log/orangehrm.log 
Above log file not generating on the live server to check the error.

**Comment by yash19070** [comment]
hello 
please provide screenshot of error and URL also.
thank you

**Comment by mostafa-zaied** [comment]
![image](https://user-images.githubusercontent.com/63561762/136715874-33aad4eb-d6b7-4892-9894-0b7e3722dd31.png)
![image](https://user-images.githubusercontent.com/63561762/136715882-dbf3209c-acbe-4f0c-bff1-918793ff59d7.png)
I'm also have Internal Error Occurred
Tried to
php symfony cc
php symfony doctrine:build-model
php symfony orangehrm:publish-assets
But the same Error

**Comment by yash19070** [comment]
check local listen ip
thank you

**Comment by mostafa-zaied** [comment]
@yash19070 
This is my `docker-compose.yaml`
```
version: "3.8"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=newDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - ALLOW_EMPTY_PASSWORD=NO
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:

```
